<a href="https://colab.research.google.com/github/DiegoRoyGulytMamaniChura/Bootcamp_DSRP/blob/main/8_NumPy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Manipulacion y Transformación de Datos con Pandas y NumPy

## ¿Por qué NumPy?
NumPy es una biblioteca en Python que se utiliza principalmente para realizar cálculos en arrays y matrices. Es especialmente útil para tareas de álgebra lineal, cálculo y modelado de datos científicos.

- ¿Profesor que es un Array?. Es una lista organizada de numeros
- ¿Profesor, y porque NumPy?
- Las Razones:
  - Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
  - Optimiza el almacenamiento en memoria.
  - Además, maneja distintos tipos de datos.
  - Es una librería muy poderosa, se pueden crear redes neuronales desde cero.





## Numpy -> Arrays


*   Es una estructura de datos que almacena una colección de elementos, generalmente del mismo tipo, en una única variable. Los elementos se pueden acceder mediante índices, que son números enteros que indican la posición del elemento dentro del arreglo. En lenguajes de programación como Python, los arrays son estructuras de datos muy utilizadas para representar listas, secuencias y otros tipos de colecciones.




In [ ]:
"""
Para los que usen jupyter, tienen que instalar con el siguiente comando:
pip install numpy
"""

#Como trabajamos en numpy, o mejor dicho como importamos

import numpy as np


## Nivel Básico

#### Array Unidimensional

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#Forma para convertir una Lista en un Array
array = np.array(lista)

In [ ]:
type(array)

numpy.ndarray

Array Bidimensional : Matriz

In [ ]:
#Esta es una Matriz 2x3
array2 = np.array([[1, 2, 3], [4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

#### Ejercicios:

*   Ejercicio 1: Crea un array unidimensional con los números del 5 al 10.
*   Ejercicio 2: Crea un array bidimensional de forma 3×3 que contenga los númerosd el 1 al 9.


In [ ]:
#SOL 1:

array1 = [5,6,7,8,9,10]
array1 = np.array(array1)

type(array1)

print(array1)

[ 5  6  7  8  9 10]


In [ ]:
#SOL 2:

array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
type(array2)

print(array2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Indexación y Slicing
Puedes acceder a elementos individuales y también usar "slicing" para acceder a sub-arrays.

In [ ]:
#Acceder a un elemento (Indexacion)

#        0 1 2 3 4 5 6 7 8
lista = [1,2,3,4,5,6,7,8,9]
array = np.array(lista)

print(array[0])
print(array[3])


1
4
[3 4 5 6 7]


In [ ]:
#Slicing
#       0 1 2 3 4 5 6 7 8 9
lista = [1,2,3,4,5,6,7,8,9]
array = np.array(lista)

print(array[1:3])
print(array[4:9])
print(array[4: ])
print(array[:8])


[2 3]
[5 6 7 8 9]
[5 6 7 8 9]
[1 2 3 4 5 6 7 8]


Ejercicios:

*   Ejercicio 3: Accede al último elemento de un array unidimensional de tu elección.
*   Ejercicio 4: Crea un array bidimensional y accede a una de sus submatrices.



In [ ]:
#SOL:
#         0 1 2 3 4 5 6 7 8
array1 = [1,2,3,4,5,6,7,8,9]
#        -9-8-7-6-5-4-3-2-1
array1 = np.array(array1)

print(array[8])
print(array[-1])


9
9


In [ ]:
#SOL:
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array2[1])
print(array2[0])


[4 5 6]
[1 2 3]


#### Operaciones Básicas

In [ ]:
#Suma de ARRAYS
#Ejemplo 1:

sum_array= np.array([1,2,3]) + np.array([4,5,6])
print("suma: ",sum_array)

#Resta de Arrays
#Ejemplo2:

rest_array= np.array([4,5,6]) - np.array([1,2,3])
print("resta: ",rest_array)

rest_array= np.array([1,2,3]) - np.array([4,5,6])
print("resta: ",rest_array)


suma:  [5 7 9]
resta:  [3 3 3]
resta:  [-3 -3 -3]


In [ ]:
#Ejemplo 2:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma =a + b

print(suma)

resta = b - a

print(resta)

[5 7 9]
[3 3 3]


Ejercicios:


*   Ejercicio 5: Multiplica dos arrays: array1 = [5,6] y array2 = [3,2]
*   Ejercicio 6: Multiplicación de array bidimensional por un escalar array([1,2,3])*2


In [ ]:
#SOL 5:
array1 = [5,6]
array1= np.array(array1)

array2 = [3,2]
array2= np.array(array2)

multi_array = array1 * array2

print(multi_array)

[15 12]


In [ ]:
#SOL 6:
array3 = np.array([[1,2,3],[4,5,6]])

mult2=array3*2

print(mult2)

[[ 2  4  6]
 [ 8 10 12]]


## Nivel Intermedio


### Manipulación de forma

*   NumPy permite cambiar la forma y la estructura de los arrays sin alterar los datos subyacentes.

In [ ]:
#Convertir un array en una matriz .reshape()

a = np.array([1, 2, 3, 4])
reshaped = a.reshape(2, 2)

reshaped

array([[1, 2],
       [3, 4]])

In [ ]:
#Convertir una matriz en un array

b = np.array([[1, 2], [3, 4]])
flattened = b.flatten()

flattened

array([1, 2, 3, 4])

### Inspeccion de una matriz

*  Si es una matriz 1D o 2D o más. (usar `ndim`)
*  Cuántos elementos están presentes en cada dimensión (use `shape`)
*  ¿Cuál es su tipo de datos (uso `dtype`)
*  ¿Cuál es el número total de elementos en él (uso `size`)
*  Muestras de los primeros elementos de la matriz (a través de la indexación)
*  Tamaño (en bytes) de cada elemento de una matriz NumPy (usa `itemsize`)

In [ ]:
lista = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr = np.array(lista, dtype='float')
arr

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [ ]:
print('Shape: ', arr.shape)
print('Datatype: ', arr.dtype)
print('Size: ', arr.size)
print('Num Dimensions: ', arr.ndim)
print('Tamaño de elemento en bytes: ', arr.itemsize)

Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2
Tamaño de elemento en bytes:  8


Ejercicios:

*   Ejercicio 8: Convierte un array de forma 5×3 a 3×5.
*   Ejercicio 9: Aplana un array bidimensional de tu elección.



In [ ]:
#SOL 1:

e1 = np.array([[1, 2, 3],
               [3, 4, 5],
               [5, 6, 7],
               [7, 8, 9],
               [1,1,1]]).reshape(3,5)

print(e1)

[[1 2 3 3 4]
 [5 5 6 7 7]
 [8 9 1 1 1]]


In [ ]:
#SOL 2:
e2 = np.array([[9, 8], [7, 6]]).flatten()
e2

array([9, 8, 7, 6])

### Funciones matemáticas y estadisticas

*   NumPy viene con una variedad de funciones matemáticas y estadisticas para operar en arrays.




In [ ]:
#Numeros random con randint('numero_inicial','numero_final','cantidad')
import numpy as np

a1 = np.random.randint(1,20,10)
a1

array([10, 19, 15, 14,  6,  9, 11, 15, 13, 15])

In [ ]:
#Ejemplo suma:
sum = np.sum(a1)
print(sum)



127


In [ ]:
# Suponiendo que ya tienes un array 'arr' definido, por ejemplo:

arr = np.array([ 5.90, 2.3, 4.66, 6.33 , 1.52, 3.14 ])
np.array(arr, dtype='float')

print('Datatype: ', arr.dtype)
print('Size: ', arr.size)

print("\n Operaciones Matematicas")

print("Suma es: ", arr.sum())
print("Max Valor es: ", arr.max())
print("Min valor es: ", arr.min())

print("\n Operaciones Estadisticas")

print("Promedio: ",arr.mean())
print("Mediana:", np.median(arr))
print("Desviacion Estandar:", arr.std())
print("Variacion :", arr.var())

print("\n Operaciones Adicionales")

print("Valor raiz cuadrada:", np.sqrt(arr))
print("Redondeo:", np.round(np.sqrt(arr),2))
print("Numeros Abs", np.abs(np.sqrt(arr)))
print(np.round(np.abs(np.sqrt(arr))))



Datatype:  float64
Size:  6

 Operaciones Matematicas
Suma es:  23.849999999999998
Max Valor es:  6.33
Min valor es:  1.52

 Operaciones Estadisticas
Promedio:  3.9749999999999996
Mediana: 3.9000000000000004
Desviacion Estandar: 1.7912169978350847
Variacion : 3.208458333333334

 Operaciones Adicionales
Valor raiz cuadrada: [2.42899156 1.51657509 2.15870331 2.51594913 1.2328828  1.77200451]
Redondeo: [2.43 1.52 2.16 2.52 1.23 1.77]
Numeros Abs [2.42899156 1.51657509 2.15870331 2.51594913 1.2328828  1.77200451]
[2. 2. 2. 3. 1. 2.]


### Operaciones en Array y Matrices




#### Operaciones de Array

In [ ]:
import numpy as np
#Arrange() es una funcion que crea una array en con la cantidad de numeros deseados

arr =np.arange(0,10)

#       1 2 3 4 5 6 7 8 9 10
#arr = (0,1,2,3,4,5,6,7,8,9)
#
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Sumamos + 2
suma = arr + 2
print("suma :",suma)


[2 3 4 5 6 7]


In [ ]:
#Resta - 1
resta = arr - 2
print("resta :",resta)


[-2 -1  0  1  2  3]


In [ ]:
#Division
div =arr/3
print(np.round(div,2))

[0.   0.33 0.67 1.   1.33 1.67]


In [ ]:
#Potencia
pot =arr**2
print(pot)

[ 0  1  4  9 16 25]


#### Operaciones con Matrices


In [ ]:
arr = np.arange(0,20)
print("Array Original : ",arr,"\n")

matriz_1 = arr.reshape(4, 5)
print("Matriz 1 :")
matriz_1


Array Original :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

Matriz 1 :


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr = np.arange(21,41)
print("Array Original : ",arr,"\n")

matriz_2 = arr.reshape(4, 5)
print("Matriz 2 :")
matriz_2




Array Original :  [21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40] 

Matriz 2 :


array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [ ]:
# Primera matriz

print("Matriz 1:")
print(matriz_1, "\n")

# Segunda matriz
print("Matriz 2:")
print(matriz_2, "\n")


# Suma de Matriz
suma_matriz = matriz_1+matriz_2
print("Suma de Matrices:")
print(suma_matriz)

Matriz 1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Matriz 2:
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]] 

Suma de Matrices:
[[21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]]


In [ ]:
# Resta de Matriz
resta_matriz = matriz_2-matriz_1

print("Resta de Matrices:")
print(resta_matriz)



Resta de Matrices:
[[21 21 21 21 21]
 [21 21 21 21 21]
 [21 21 21 21 21]
 [21 21 21 21 21]]


#### Transposicion de Matrices

In [ ]:
#Matriz Transpuesta pasa de 4x5 a 5x4:
matriz_t1 = matriz_1.T
print("Matriz Transpuesta 1:")
print(matriz_t1,"\n")


matriz_t2 = matriz_2.T
print("Matriz Transpuesta 2:")
print(matriz_t2)

Matriz Transpuesta 1:
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] 

Matriz Transpuesta 2:
[[21 26 31 36]
 [22 27 32 37]
 [23 28 33 38]
 [24 29 34 39]
 [25 30 35 40]]


In [ ]:
#Multiplicacion:
matriz_mult = matriz_t1*matriz_t2
print("Multiplicacion de Matrices:")
print(matriz_mult)

Multiplicacion de Matrices:
[[  0 130 310 540]
 [ 22 162 352 592]
 [ 46 196 396 646]
 [ 72 232 442 702]
 [100 270 490 760]]


## EJERCICIOS:

### Ejercicio 1: Creación y Manipulación de Arreglos

1. Crea un arreglo unidimensional que contenga los números del 1 al 10.
2. Crea un arreglo bidimensional de forma \(3 \times 3\) con números del 1 al 9.
3. Utiliza el método `reshape` para convertir el arreglo unidimensional del punto 1 en un arreglo bidimensional de forma \(2 \times 5\).


In [ ]:
lista=[1,2,3,4,5,6,7,8,9,10]

print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
reshaped=a.reshape(2,5)
reshaped



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Ejercicio 2: Indexación y Slicing

Dado el arreglo bidimensional:


\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}


Realiza las siguientes operaciones:

1. Extrae el número 5 de la matriz.
2. Obtén la primera fila.
3. Obtén la última columna.
4. Utiliza slicing para obtener la submatriz
\begin{pmatrix} 5 & 6 \\ 8 & 9 \end{pmatrix}


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened=b.flatten()
flattened
ultima_columna = [fila[-1] for fila in b]

print(flattened[4])
print(b[0])
print(ultima_columna)
print(b[1:, 1:])

5
[1 2 3]
[3, 6, 9]
[[5 6]
 [8 9]]



### Ejercicio 3: Operaciones Matemáticas

1. Crea dos arreglos unidimensionales \( A \) y \( B \) de la misma longitud, llenos de números aleatorios.
2. Calcula la suma \( A + B \).
3. Calcula el producto punto \( A \cdot B \).
4. Encuentra el valor máximo en el arreglo \( A + B \) y su correspondiente índice.

Estos ejercicios cubren las operaciones básicas de NumPy y deberían proporcionar una buena práctica para los estudiantes que están empezando.

In [ ]:
A = [0,1,2,3,4,5,6,7,8,9,10,12]
B = [50,51,52,53,54,55,56,57,58,59,60,61]
C= A+B
maximo=max(C)
print(A+B)
producto_punto=np.dot(A,B)
print(producto_punto)
print(maximo)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61]
3867
61
